// ... previous content

export const BUTTON_TEXT = {
     // ... existing
    JOIN_EVENT: 'Join Event',
    SOLD_OUT: 'Sold Out',
    GOING: '✓ Going',
    CANCEL: 'Cancel',
    CHECK_IN: 'Check In',
    LEAVE_COMMUNITY: 'Leave Community',
    JOIN_COMMUNITY: 'Join Community',
    VIEW_ON_MAP: 'View on Map',
    MANAGE_EVENT: 'Manage Event',
    ADD_TO_CALENDAR: 'Add to Calendar',
    SAVE_CHANGES: 'Save Changes',
    CREATE_EVENT: 'Create Event',
};

export const ERROR_MESSAGES = {
    // ... existing
    RSVP_FAILED: 'Failed to update RSVP',
    IMAGE_LOAD_FAILED: 'Failed to load image',
    GENERIC_ERROR: 'An unexpected error occurred',
    NOT_FOUND: 'Resource not found',
    // New
    CHECK_IN_SUCCESS: 'Check-in Successful!',
    TICKET_VALID: 'Ticket valid.',
    INVALID_TICKET: 'Invalid Ticket',
    EVENT_SAVE_ERROR: 'Failed to save event.',
    EVENT_UPDATED: 'Event updated successfully!',
    EVENT_CREATED: 'Event created successfully!',
    COMMUNITY_LOAD_ERROR: 'Failed to load communities',
};

export const UI_TEXT = {

    NO_IMAGE: 'No Image',
    CLICK_TO_VIEW: 'Click to view details',
    JOINED_BADGE: 'JOINED',
    Loading: 'Loading...',
    GOING_COUNT_SUFFIX: 'going',
    EVENT_NOT_FOUND: 'Event not found',
    WHEN_LABEL: 'When',
    WHERE_LABEL: 'Where',
    EVENT_DESCRIPTION_TITLE: 'Event Description',
    LOCATION_TITLE: 'Location',
    PHOTO_GALLERY_TITLE: 'Photo Gallery',
    ADD_PHOTO_LABEL: 'Add Photo',
    ADD_MEMORY_LABEL: 'Add Memory',
    NO_PHOTOS_MESSAGE: 'No photos yet.',
    ORGANIZED_BY_LABEL: 'Organized by',
    DEFAULT_ORGANIZER_NAME: 'Organizer',
    ATTENDEES_LABEL: 'Attendees',
    // CheckIn & Scanner
    EVENT_CHECK_IN_TITLE: 'Event Check-in',
    SCAN_TICKET_TITLE: 'Scan Ticket',
    SCAN_INSTRUCTION: "Point camera at the attendee's QR code",
    MANUAL_ENTRY_PROMPT: 'Or enter code manually via',
    ATTENDEE_LIST_LINK: 'Attendee List',
    // Event Form
    EDIT_EVENT_TITLE: 'Edit Event',
    CREATE_EVENT_TITLE: 'Create New Event',
    EDIT_EVENT_SUBTITLE: 'Update your event details below.',
    CREATE_EVENT_SUBTITLE: 'Fill in the details below to host your event.',
    EVENT_TITLE_LABEL: 'Event Title',
    EVENT_TITLE_PLACEHOLDER: 'e.g., Annual Block Party',
    COVER_IMAGE_LABEL: 'Event Cover Image',
    DESCRIPTION_LABEL: 'Description',
    DESCRIPTION_PLACEHOLDER: 'Describe your event...',
    CATEGORY_LABEL: 'Category',
    VISIBILITY_LABEL: 'Visibility',
    PUBLIC_OPTION: 'Public (Everyone)',
    COMMUNITY_ONLY_OPTION: 'Community Members Only',
    PRIVATE_OPTION: 'Private (Invite Only)',
    HOST_COMMUNITY_LABEL: 'Host Community',
    SELECT_COMMUNITY_PLACEHOLDER: 'Select a Community',
    INVITE_EMAILS_LABEL_REQUIRED: 'Invitee Emails (Required)',
    INVITE_EMAILS_LABEL_OPTIONAL: 'Invite People (Optional)',
    INVITE_EMAILS_PLACEHOLDER: 'Enter email addresses separated by commas (e.g., alice@example.com, bob@example.com)',
    PRIVATE_EVENT_NOTE: 'For private events, only people with these email addresses will be able to see and join the event.',
    COMMUNITY_WARNING: '⚠️ You selected "Community Members Only". Please select a community to associate this event with, or it will not be visible to the right people.',
    START_DATE_LABEL: 'Start Date & Time',
    END_DATE_LABEL: 'End Date & Time',
    LOCATION_DETAILS_TITLE: 'Location Details',
    VENUE_ADDRESS_LABEL: 'Venue Address',
    VENUE_ADDRESS_PLACEHOLDER: '123 Main St, City',
    PICK_LOCATION_LABEL: 'Pick Location on Map',
    ADDITIONAL_SETTINGS_TITLE: 'Additional Settings',
    CAPACITY_LABEL: 'Capacity',
    RECURRING_EVENT_LABEL: 'This is a recurring event',
    FREQUENCY_LABEL: 'Frequency',
    INTERVAL_LABEL: 'Interval',
    END_DATE_RECURRENCE_LABEL: 'End Date',
    FREQUENCY_DAILY: 'Daily',
    FREQUENCY_WEEKLY: 'Weekly',
    FREQUENCY_MONTHLY: 'Monthly',
    // Discover Page
    DISCOVER_TITLE: 'Discover',
    EVENTS_TAB: 'Events',
    COMMUNITIES_TAB: 'Communities',
    ALL_FILTER: 'All',
    DISCOVER_HERO_TITLE_PREFIX: 'Discover What\'s',
    DISCOVER_HERO_TITLE_SUFFIX: 'Happening',
    DISCOVER_HERO_SUBTITLE: 'Explore workshops, meetups, and local events specifically curated for your community interests.',
    SEARCH_PLACEHOLDER: 'Search by title...',
    NEAR_ME_LABEL: 'Near Me',
    NEARBY_LABEL: 'Nearby',
    CLEAR_ACTION: 'Clear',
    UPCOMING_EVENTS_TITLE: 'Upcoming Events',
    LATEST_LABEL: 'Latest',
    NO_EVENTS_FOUND_TITLE: 'No events found',
    NO_EVENTS_FOUND_SUBTITLE: 'Try adjusting your search terms or check back later.',
    // Dashboard
    LOADING_DASHBOARD: 'Loading your dashboard...',
    SESSION_EXPIRED_TITLE: 'Session Expired',
    SESSION_EXPIRED_MESSAGE: 'Please log in again to access your dashboard features.',
    GO_TO_LOGIN: 'Go to Login',
    OOPS_ERROR: 'Oops! Something went wrong',
    // Attendee Manager (Moved to bottom)
    // Image Upload
    UPLOAD_PREVIEW_ALT: 'Preview',
    UPLOAD_FAILED: 'Failed to upload image',
    UPLOADING_LABEL: 'Uploading...',
    CLICK_TO_UPLOAD: 'Click to upload cover image',
    UPLOAD_HINT: 'JPG, PNG up to 5MB',
    // Notifications
    NOTIFICATIONS_TITLE: 'Notifications',
    MARK_ALL_READ: 'Mark all read',
    NO_NOTIFICATIONS: 'No notifications yet',
    // Layout
    BRAND_NAME: 'EventSphere',
    NAV_DISCOVER: 'Discover',
    NAV_DASHBOARD: 'Dashboard',
    NAV_SIGN_OUT: 'Sign Out',
    NAV_SIGN_IN: 'Sign In',
    NAV_GET_STARTED: 'Get Started',
    // Footer
    FOOTER_TAGLINE: 'Connecting communities through real-world events. Join us to discover, host, and participate.',
    FOOTER_PLATFORM: 'Platform',
    FOOTER_COMMUNITY: 'Community',
    FOOTER_CONTACT: 'Contact',
    FOOTER_FEATURES: 'Features',
    FOOTER_PRICING: 'Pricing',
    FOOTER_SIGN_UP: 'Sign Up',
    FOOTER_BECOME_ORGANIZER: 'Become an Organizer',
    FOOTER_GUIDELINES: 'Guidelines',
    FOOTER_COPYRIGHT: 'EventSphere. All rights reserved.',
    // Dashboard Layout
    DASHBOARD_WELCOME: 'Welcome back',
    DASHBOARD_SUBTITLE: 'Here\'s what\'s happening with your events.',
    BROWSE_EVENTS: 'Browse Events',
    SIDEBAR_JOINED: 'Joined Events',
    SIDEBAR_DISCOVER: 'Discover Events',
    SIDEBAR_MANAGEMENT: 'Management',
    SIDEBAR_MY_EVENTS: 'My Events',
    SIDEBAR_CREATE_EVENT: 'Create Event',
    SIDEBAR_ADMIN: 'System Admin',
    ROLE_ORGANIZER: 'Organizer',
    ROLE_ADMIN: 'Admin',
    ROLE_DASHBOARD: 'Dashboard',

    // Home Page
    HOME_HERO_BADGE: 'The Ultimate Community Platform',
    HOME_HERO_TITLE_PREFIX: 'Connect with your',
    HOME_HERO_TITLE_HIGHLIGHT: 'Community',
    HOME_HERO_SUBTITLE: 'Discover local events, join neighborhood associations, and connect with hobby groups. EventSphere brings people together in the real world.',
    HOME_HERO_CTA_DISCOVER: 'Discover Events',
    HOME_HERO_CTA_GET_STARTED: 'Get Started',
    HOME_HERO_CTA_MY_DASHBOARD: 'My Dashboard',
    HOME_HERO_CTA_DASHBOARD: 'Dashboard',

    HOME_USE_CASES_TITLE: 'Designed for Every Community',
    HOME_USE_CASES_SUBTITLE: 'Whether you are a neighbor, a hobbyist, or a business owner.',
    
    HOME_UC_HOA_TITLE: 'Neighborhood Associations',
    HOME_UC_HOA_DESC: 'Manage HOA meetings, block parties, and local updates with private community events.',
    HOME_UC_HOBBY_TITLE: 'Hobby Groups',
    HOME_UC_HOBBY_DESC: 'Organize weekly meetups for hiking, gaming, book clubs, and shared interests.',
    HOME_UC_BIZ_TITLE: 'Local Businesses',
    HOME_UC_BIZ_DESC: 'Promote grand openings, sales, and workshops to your local audience.',

    HOME_FEATURES_TITLE: 'Everything You Need',
    HOME_FEATURES_SUBTITLE: 'Powerful features to manage successful events.',
    
    HOME_FEAT_CREATION_TITLE: 'Event Creation',
    HOME_FEAT_CREATION_DESC: 'Easy scheduling with date, time, and capacity limits.',
    HOME_FEAT_PRIVACY_TITLE: 'Privacy Controls',
    HOME_FEAT_PRIVACY_DESC: 'Public, Community-only, or Private Invite visibility.',
    HOME_FEAT_MAPS_TITLE: 'Interactive Maps',
    HOME_FEAT_MAPS_DESC: 'Find events near you with geolocation.',
    HOME_FEAT_ATTENDEES_TITLE: 'Attendee Management',
    HOME_FEAT_ATTENDEES_DESC: 'Track RSVPs and manage guest lists.',
    HOME_FEAT_NOTIFS_TITLE: 'Smart Notifications',
    HOME_FEAT_NOTIFS_DESC: 'Automated email updates for attendees.',
    HOME_FEAT_CHECKIN_TITLE: 'Event Check-in',
    HOME_FEAT_CHECKIN_DESC: 'Seamless QR or manual check-in on event day.',
    HOME_FEAT_GALLERY_TITLE: 'Photo Gallery',
    HOME_FEAT_GALLERY_DESC: 'Share memories from past events.',
    HOME_FEAT_DISCUSS_TITLE: 'Discussions',
    HOME_FEAT_DISCUSS_DESC: 'Q&A section for every event.',
    HOME_FEAT_RECUR_TITLE: 'Recurring Events',
    HOME_FEAT_RECUR_DESC: 'Schedule weekly or monthly meetups easily.',
    HOME_FEAT_DISCOVERY_TITLE: 'Discovery',
    HOME_FEAT_DISCOVERY_DESC: 'Interest-based search and categories.',
    HOME_FEAT_CALENDAR_TITLE: 'Calendar Sync',
    HOME_FEAT_CALENDAR_DESC: 'Add events directly to Google Calendar.',

    HOME_CTA_TITLE: 'Ready to Lead Your Community?',
    HOME_CTA_DESC: 'Become an organizer today to access advanced tools, analytics, and community management features. Admins review every application to ensure quality.',
    HOME_CTA_CREATE_EVENT: 'Create Event',
    HOME_CTA_BECOME_ORGANIZER: 'Become an Organizer',
    HOME_CTA_SIGN_UP: 'Sign Up Now',

    // Auth Forms
    AUTH_EMAIL_LABEL: 'Email',
    AUTH_EMAIL_PLACEHOLDER: 'you@example.com',
    AUTH_PASSWORD_LABEL: 'Password',
    AUTH_PASSWORD_PLACEHOLDER: '••••••••',
    AUTH_NAME_LABEL: 'Full Name',
    AUTH_NAME_PLACEHOLDER: 'John Doe',
    AUTH_CONFIRM_PASSWORD_LABEL: 'Confirm Password',
    
    AUTH_SIGN_IN_BUTTON: 'Sign In',
    AUTH_SIGN_UP_BUTTON: 'Sign Up',
    AUTH_VERIFY_BUTTON: 'Verify & Complete Signup',
    AUTH_RESEND_CODE: 'Resend Code',
    
    AUTH_NO_ACCOUNT: "Don't have an account?",
    AUTH_CREATE_ONE: 'Create one',
    AUTH_HAS_ACCOUNT: 'Already have an account?',
    AUTH_SIGN_IN_LINK: 'Sign in',
    AUTH_CODE_NOT_RECEIVED: "Didn't receive the code?",
    
    AUTH_VERIFY_CODE_LABEL: 'Verification Code',
    AUTH_VERIFY_PLACEHOLDER: '000000',

    // Auth Messages
    AUTH_LOGIN_SUCCESS: 'Logged in successfully!',
    AUTH_REGISTER_SUCCESS: 'Registration successful! Please check your email for the OTP.',
    AUTH_VERIFY_SUCCESS: 'Email verified successfully!',
    AUTH_VERIFY_INVALID_LENGTH: 'Please enter a 6-digit code',
    AUTH_RESEND_SUCCESS: 'A new code has been sent (feature coming soon!)',
    AUTH_LOGIN_FAILED: 'Login failed',
    AUTH_REGISTER_FAILED: 'Registration failed',
    AUTH_VERIFY_FAILED: 'Verification failed',
    AUTH_UNEXPECTED_ERROR: 'An unexpected error occurred',

    // Community
    COMMUNITY_LOADING: 'Finding communities near you...',
    COMMUNITY_EMPTY: 'No communities found. Be the first to start one!',
    COMMUNITY_JOIN_SUCCESS: 'Joined community successfully!',
    COMMUNITY_JOIN_FAILED: 'Failed to join',
    COMMUNITY_NEARBY: 'Nearby',
    COMMUNITY_MEMBERS_SUFFIX: 'Members',
    COMMUNITY_JOINED_BADGE: '✅ Joined',
    COMMUNITY_VIEW_DETAILS: 'View Details',
    COMMUNITY_JOIN: 'Join Community',
    
    // Event Items
    EVENT_ITEM_ONLINE: 'Online',
    EVENT_ITEM_TICKET: 'Ticket',
    EVENT_ITEM_SHARE: 'Share',
    EVENT_ITEM_KEY_SCAN: 'Scan',
    EVENT_ITEM_KEY_MANAGE: 'Manage',
    EVENT_ITEM_JOIN_ME: 'Join me at',

    // RSVP / Attendee Manager
    ATTENDEE_LIST_HEADER: 'Guest List',
    REFRESH_BUTTON: 'Refresh',
    CHECK_IN_FAILED: 'Check-in failed',
    CHECKED_IN_STATUS: 'Checked In',
    NO_ATTENDEES: 'No attendees have joined yet.',
    
    // Comments
    COMMENTS_HEADER: 'Comments',
    COMMENT_PLACEHOLDER: 'Share your thoughts...',
    COMMENT_POST_BUTTON: 'Post Comment',
    COMMENT_REPLY_BUTTON: 'Reply',
    COMMENT_DELETE_CONFIRM: 'Delete this comment?',
    COMMENT_LOGIN_PROMPT: 'Please sign in to leave a comment.',
    COMMENT_LOAD_MORE: 'Load More Comments',
    COMMENT_REPLY_PLACEHOLDER: 'Write a reply...',

    // Dashboard / User
    USER_DASHBOARD_WELCOME: 'Welcome,',
    USER_DASHBOARD_SUBTITLE: 'Ready to discover your next experience?',
    DASHBOARD_DISCOVER_BTN: 'Discover Events',
    DASHBOARD_PENDING_TITLE: 'Application Pending',
    DASHBOARD_PENDING_MSG: 'We are reviewing your request to become an Organizer. You will be notified soon.',
    DASHBOARD_JOINED_EVENTS: 'Your Joined Events',
    DASHBOARD_NO_EVENTS_TITLE: 'No joined events yet',
    DASHBOARD_NO_EVENTS_MSG: 'Discover amazing things happening in your community.',
    DASHBOARD_BROWSE_EVENTS: 'Browse Events',
    DASHBOARD_TICKET_TITLE: 'Your Ticket',
    DASHBOARD_TICKET_SUB: 'Scan this at the entrance',
    
    // Upgrade Section
    UPGRADE_TITLE: 'Become a Community Leader',
    UPGRADE_DESC: 'Take the next step. Create and manage events for your neighborhood, hobby group, or local business.',
    UPGRADE_ITEM_NEIGHBORHOOD: 'Neighborhood Communities',
    UPGRADE_ITEM_HOBBY: 'Hobby & Interest Groups',
    UPGRADE_ITEM_BUSINESS: 'Local Businesses',
    UPGRADE_CARD_TITLE: 'Ready to Host?',
    UPGRADE_CARD_DESC: 'Get access to attendee management, check-ins, and event analytics.',
    UPGRADE_BTN: 'Upgrade to Organizer',
    UPGRADE_NOTE: 'Verification takes less than 24 hours.',
    UPGRADE_SUCCESS: 'Upgrade request submitted! An admin will review it shortly.',
    UPGRADE_FAILED: 'Failed to submit request',

    // Admin
    ADMIN_DASHBOARD_TITLE: 'Admin Dashboard',
    ADMIN_PENDING_TITLE: 'Pending Upgrade Requests',
    ADMIN_NO_REQUESTS: 'No pending requests found.',
    ADMIN_TABLE_USER: 'User',
    ADMIN_TABLE_EMAIL: 'Email',
    ADMIN_TABLE_REGISTERED: 'Registered',
    ADMIN_TABLE_ACTIONS: 'Actions',
    ADMIN_APPROVE: 'Approve',
    ADMIN_REJECT: 'Reject',
    ADMIN_LOAD_ERROR: 'Failed to load requests',
    ADMIN_APPROVE_SUCCESS: 'User upgraded successfully',
    ADMIN_APPROVE_ERROR: 'Failed to approve user',
    ADMIN_REJECT_SUCCESS: 'Request rejected',
    ADMIN_REJECT_ERROR: 'Failed to reject request',

    // Past Events
    PAST_EVENTS_TITLE: 'Recent Memories',
    PAST_EVENTS_SUBTITLE: 'See what our community has been up to.',
};

// ... existing DATE_FORMATS


export const DATE_FORMATS = {
    EVENT_CARD: 'EEE, MMM d • h:mm a',
    EVENT_DETAILS_DATE: 'PPPP',
    EVENT_DETAILS_TIME: 'p',
};
